### PR TITLE
Add ability to retrieve return values from handlers

### PR DESCRIPTION
**Pull request by nathan-king**
Currently the bus just dispatches commands to a handler, but has no way of handling return values. Some handlers may provide proxy to the domain layer, and thus return values can be useful.

**Use case**

```php
$user = $bus->dispatch(new GetUserByIdCommand('767ba388-186e-40ec-b281-14633b8dcbcb'));
```

### CODE REVIEW

**Comment by 0x13a** [comment]
when using commands you follow the Command-query separation (CQS) principle: a function is either a query (i.e. it returns something) or a command (i.e. it affects state). Both are mutually exclusive. So a command is not supposed to return anything and a query is not supposed to modify anything. 
Thanks for the PR anyway. I'm opened to discussion if you've good arguments.

**Comment by nathan-king** [comment]
Just because you're using a command bus doesn't mean you're using the CQS principle. It's perfectly acceptable to use a command bus as a proxy between your application and domain layers.

It should be left up to the discretion of the developer on whichever route they choose; if you decide that they aren't allowed to have commands that can return values for them, you're no better than Taylor Otwell.

**Comment by Ocramius** [comment]
`$bus->dispatch(new GetUserByIdCommand('767ba388-186e-40ec-b281-14633b8dcbcb'))`

This is not a command, it's a query. Use a query bus for that, or even just a repository, directly.

Given that the abstraction of the command bus (its interface) advantages are for:

 * internal routing
 * asynchronous delivery
 * piping intermediate steps (middleware)

If you *really* want to return something, return a promise (since execution may be deferred) or a delivery ID with which you can track command execution (promise to be built manually).

First one probably being the best approach.

Still, since the command bus may span across different address spaces (when using a message queue emitter), you can't really allow non-serializable values to be passed through, so you have quite a headscratcher.

A promise that resolves with some execution metadata (delivery id, command id, for example) would be best. Returning what the command internally does: no-go.

**Comment by nathan-king** [comment]
Again, just because you're using a command bus doesn't mean you're using the CQS principle. 

```
The most common style of interface to a module is to use procedures, or object methods. So if you want a module to calculate a bunch of charges for a contract, you might have a BillingService class with a method for doing the calculation, calling it like this $billingService->calculateCharges($contract);. 

A command oriented interface would have a command class for each operation, and be called with something like this $cmd = new CalculateChargesCommand($contract); $cmd->execute();. Essentially you have one command class for each method that you would have in the method-oriented interface. A common variation is to have a separate command executor object that actually does the running of the command. $command = new CalculateChargesCommand($contract); $commandBus->execute($command);
```
-- From [Martin Fowler's Blog](https://martinfowler.com/bliki/CommandOrientedInterface.html) (code samples haven ported to PHP)

**Comment by 0x13a** [comment]
Thanks @Ocramius !
@nathan-king I agree with 

> A command oriented interface would have a command class for each operation

But where is written in the article, that the command should return the execution result ?
And again it's not just about using or not CQS. Using a command for retrieving things, it's not more that using an application service, it's not what the Command Bus it's meant to be. As @Ocramius said: 

> Returning what the command internally does: no-go

**Pull request closed without merging**
